# -*- coding: utf-8 -*-
"""EigenValue&Vector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gB4uJN_3-6LS6dwALhNFgGQOTK9b42oL
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

A = np.array([[1,0],[0,-2]])
print(A)

results = la.eig(A)

print(results[0])

print(results[1])

eigvals, eigvecs = la.eig(A)
print(eigvals)

eigvals, eigvecs = la.eig(A)
print(eigvals)

print(eigvecs)

# .real to convert the array of eigenvalues to real numbers:
eigvals = eigvals.real
print(eigvals)

lambda1 = eigvals[1]
print(lambda1)

v1 = eigvecs[:,1].reshape(2,1)
print(v1)

A @ v1

lambda1 * v1

